### PR TITLE
Adjust RouteMetric and add DEBUG logs

### PR DESCRIPTION
**Pull request by olnrao**

### CODE REVIEW

**Comment by Joscorbe** [comment]
The script worked perfectly for me after @olnrao's changes. Thanks!

**Comment by ctrubian** [comment]
+1 to this PR, i had to make a similar change locally to get the script to work.  Otherwise this script is making my life so much easier.

**Comment by adam-ut** [comment]
+1 on this PR. @deanmcniven

**Comment by chizou** [comment]
Thanks! I needed these changes to make it work as well

**Review by dmcniven — APPROVED** [review]

**Pull request merged**
